### ISSUE TITLE
Automatically squeeze DSS file when needed

### ISSUE THREAD

**Issue by bradtom** [CADWRDeltaModeling/pyhecdss#17]
* pyhecdss version: 0.2.5
* Python version: 3.7.3
* Operating System: Windows 10

### Description

I had a dss file that pyhecdss was unable to catalog. After squeezing the file with HEC Dss Vue, pyhecdss was able to catalog it. The method pyhecdss.read_catalog() was returning None, resulting in an error in  the method pyhecdss.get_pathnames(), in the line "pdf=catalog_dataframe.iloc[:,[1,2,3,6,5,4]]". I suggest modifying one of the methods to call another method to squeeze the file when necessary.

**Comment by dwr-psandhu** [comment]
I can wrap the zcofil method in heclib which is what is called by "squeeze" function in dssutl. It is essenitally a "brute force" copy of the contents of the DSS file. I leave it to the user to decide when to squeeze the file. Perhaps a warning if the catalog fails would be to include the instructions to call zcofil method. The user can then wrap the exception and check the exception message to automatically call zcofil if desired.

**Comment by dwr-psandhu** [comment]
@bradtom dssutl is already available and I don't see a need to repeat this rarely used functionality in the python modules. Furthermore there is a new release of DSS version 7 that doesn't even need this functionality. 
Closing this issue with this remark.

**Comment by bouhia30** [comment]
@dwr-psandhu , I am working currently on a .dss file with 7-IC version( Library Version: 7-IC). I am trying to use the read_catalog() method. But it doesn't work , i got this error: 
"No columns to parse from file" 

when I changed with a dss file with 6-ME version, it worked normally. 
I do not understand what is the problem .
Than you

**Comment by dwr-psandhu** [comment]
@bouhia30 This library is only mean to support version 6x only. If you are working with higher versions of DSS , you can try the python bindings https://github.com/gyanz/pydsstools for version 7+
The hec library itself is now available at https://github.com/HydrologicEngineeringCenter/hec-dss
