### ISSUE TITLE
Irregular time-series finding Illegal starting date/time

### ISSUE THREAD

**Issue by zackaryleady** [CADWRDeltaModeling/pyhecdss#19]
* pyhecdss version: 0.4.0
* Python version: 3.7.4 (64bit on win32)
* Operating System: Windows 10 64bit

### Description
I receive a forecast.dss file from DWR OCO every week for their forecast. It contains 14 regular time-series which work as expected, but it contains 1 irregular time-series with pathname:

/FORE+GATE/CHWST000/POS/28Jan2020 - 31Mar2020/IR-YEAR/DSM2-20200303-29A/

in an older forecast.dss file this path gets read in correctly, in newer forecast.dss files they do not.

The code I use to retrieve them is the same. The files look identical and use the same version ['6-KE', 6] but my software is ['6-VE, 6] if it matters.

The older forecast.dss file runs fine and the D part when I call dss_file_obj.read_catalog contains both dates and "-"; however, the newer forecast.dss file only has a single 01Jan2020 D part in the catalog and this causes an error "list index out of range" on line 443 in the read_its() function for 

tw = list(map(lambda x: x.strip(), parts[4].split("-")))

as tw only has a single element in the list instead of 2.

So why is the read_catalog() function only returning a D part of 01JAN2020 instead of 28Jan2020 - 31Mar2020?

### What I Did
Executed code test_pyhecdss_20191031.py (sent with 2 *.dss files to email).

older forecast.dss file reads everything fine.

newer forecast.dss file gives:
![image](https://user-images.githubusercontent.com/32244407/76644791-ed1be100-6514-11ea-851c-b8da25a92ebe.png)

which if you dig deeper traces back to line 443 not having two elements in tw, which is a result of the catalog dataframe D part having 01JAN2020 not 28Jan2020 - 31Mar2020.

Please let me know if you need anything else. This is critical for me to resolve.

**Comment by dwr-psandhu** [comment]
@zackaryleady I downloaded your files and ran your test and it ran fine. I did not get the error above.
I also did an interactive session and did not have a problem in reading the catalog.
Here is my speculation. Some times the catalog does not get created correctly. You can try calling catalog() method on the dss handle to redo the catalog before calling read_catalog. Alternatively you can remove *.ds* files except for *.dss ofcourse and run the script again.

**Comment by dwr-psandhu** [comment]
The issue was only with irregular time series. Cleaned up code to have both regular and irregular time series use the same time window parsing logic

**Comment by dwr-psandhu** [comment]
The issue was only with irregular time series. Cleaned up code to have both regular and irregular time series use the same time window parsing logic
