### ISSUE TITLE
Unable to open DSS file due to version incompatibility

### ISSUE THREAD

**Issue by xuhotting** [CADWRDeltaModeling/pyhecdss#34]
* pyhecdss version: '1.4.0+2.g9d14b63'
* Python version: 3.9.7
* Operating System: Win 11

### Description
Hello,

I am using the pyhecdss package to open a DSS file, but I am encountering a version incompatibility error. Could you please provide guidance on how to resolve this issue? Is there a version of pyhecdss that supports DSS file version 7-HL?

Thank you! The error message is as follows:

***** DSS: Incompatible DSS Software Versions *****
The File Specified is Version 7-HL
This Software is Version 6-WE
These Versions are Incompatible - Please Update Your DSS File, or this Program

### What I Did
import pyhecdss
dh = pyhecdss.DSSFile(fname)

**Comment by Mississippi-Valley-CA** [comment]
Hello, I am encountering this same issue with my DSS files (7-IC).  Is there a version of pyhecdss that supports DSS file version 7? Or, is there a workaround? Thank you

**Comment by dwr-psandhu** [comment]
We only did this pre DSS 7 but now the standard python library supported by HEC is the best option 

https://github.com/HydrologicEngineeringCenter/hec-dss-python
